### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by devth** [hybridgroup/artoo-arduino#11]
I'm new to artoo. The docs don't make it super clear what's going on. I ran `artoo connect scan` and saw `/dev/tty.usbmodem1411         /dev/ttys053`. So then:

```
artoo connect serial ttys053 8023
         run  socat -d -d -b57600 FILE:/dev/ttys053,nonblock,raw,echo=0 TCP-LISTEN:8023,fork from "."
```

Not sure what that did but guessing it started a server listening on 8023 to communicate with /dev/ttys053. That means I should be able to use:

```
connection :arduino, adaptor: :firmata, port: '127.0.0.1:8023'
```

in my Ruby right?
Tried and hit:

```
I, [2013-11-17T15:08:11.055911 #63213]  INFO -- : Connecting to 'arduino' on port '127.0.0.1:8023'...
E, [2013-11-17T15:08:11.060018 #63213] ERROR -- : Artoo::Adaptors::Firmata crashed!
Errno::ECONNREFUSED: Connection refused - connect(2)
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-io-0.15.0/lib/celluloid/io/tcp_socket.rb:85:in `connect_nonblock'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-io-0.15.0/lib/celluloid/io/tcp_socket.rb:85:in `initialize'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/artoo-1.4.1/lib/artoo/adaptors/adaptor.rb:70:in `new'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/artoo-1.4.1/lib/artoo/adaptors/adaptor.rb:70:in `connect_to_tcp'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/artoo-1.4.1/lib/artoo/adaptors/adaptor.rb:62:in `connect_to'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/artoo-arduino-1.3.0/lib/artoo/adaptors/firmata.rb:15:in `connect'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Users/thartman/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
E, [2013-11-17T15:08:11.060095 #63213] ERROR -- : Connection refused - connect(2)
```

am I doing something wrong?

```
± ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.4.0]
```

**Comment by deadprogram** [comment]
Looks to me like `tty.usbmodem1411` would be the expected name. So `artoo connect serial tty.usbmodem1411 8023` should work.

**Comment by solojavier** [comment]
Closing this issue. @devth please comment out if you still experience trouble with this... tty.usbmodem1411 seems to be the correct param...
